version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: GainMiles
      POSTGRES_PASSWORD: GainMiles
      POSTGRES_DB: compose_pg_for_ci_cd_practice
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_web_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 3000
      
volumes:
  pgdata: