version: '3.8'

services:
  db:
    image: postgres
    container_name: gainmiles_db
    environment:
      POSTGRES_USER: GainMiles
      POSTGRES_PASSWORD: GainMiles
      POSTGRES_DB: gain_miles
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: gainmiles_web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

volumes:
  pgdata:

networks:
  backend:
     driver: bridge